In [14]:
import requests
import bs4
from bs4 import BeautifulSoup as bs

page=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')

# page
soup=bs(page.content)
# soup

ranking=[]
player=[]
team=[]
rating=[]

# scraping data for the top player since it has a different class/attribute than the rest of the table

player1 = soup.find('tr', class_="rankings-block__banner")
ranking.append(player1.text.split('\n')[4].strip(' '))
player.append(player1.text.split('\n')[20])
team.append(player1.text.split('\n')[27])
rating.append(player1.text.split('\n')[31])

# Scraping data for the rest 9 players

for i in soup.find_all('tr', class_="table-body"):
    ranking.append(i.text.split('\n')[4].strip(' '))
    player.append(i.text.split('\n')[13])
    team.append(i.text.split('\n')[17])
    rating.append(i.text.split('\n')[19])
    
        
import pandas as pd
df=pd.DataFrame({'Ranking': ranking,'Player':player,'Team':team,'Rating':rating})
df[:10]

  Ranking            Player Team Rating
0       1   Hayley Matthews   WI    380
1       2      Ellyse Perry  AUS    374
2       3    Natalie Sciver  ENG    357
3       4       Amelia Kerr   NZ    356
4       5    Marizanne Kapp   SA    349
5       6     Deepti Sharma  IND    322
6       7  Ashleigh Gardner  AUS    270
7       8     Jess Jonassen  AUS    246
8       9    Jhulan Goswami  IND    214
9      10   Katherine Brunt  ENG    207